name: Check for update

on:
  schedule:
    - cron: '*/10 * * * *' # every minute
  workflow_dispatch: # manually run sync
  
jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for updates
        env: 
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          yarn
          node check-updates.js
